/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/utils/dl_utils/setup_env.py:56: UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  warnings.warn(
/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/utils/dl_utils/setup_env.py:56: UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  warnings.warn(
Downloading: "https://download.openmmlab.com/mmpose/v1/pretrained_models/mae_pretrain_vit_small.pth" to /home/nr4325/.cache/torch/hub/checkpoints/mae_pretrain_vit_small.pth
Traceback (most recent call last):
  File "tools/train.py", line 162, in <module>
    main()
  File "tools/train.py", line 158, in main
Traceback (most recent call last):
    runner.train()  File "tools/train.py", line 162, in <module>

    main()  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1723, in train

      File "tools/train.py", line 158, in main
self._init_model_weights()    runner.train()
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/runner/runner.py", line 906, in _init_model_weights

    model.init_weights()  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1723, in train

    self._init_model_weights()  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/model/base_module.py", line 136, in init_weights

  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/runner/runner.py", line 906, in _init_model_weights
    model.init_weights()    
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/model/base_module.py", line 136, in init_weights
m.init_weights()
    m.init_weights()  File "/home/nr4325/Desktop/Pose4/mmpose/mmpose/models/backbones/vision_transformer.py", line 384, in init_weights

  File "/home/nr4325/Desktop/Pose4/mmpose/mmpose/models/backbones/vision_transformer.py", line 384, in init_weights
    super(VisionTransformer, self).init_weights()    super(VisionTransformer, self).init_weights()
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/model/base_module.py", line 144, in init_weights

    initialize(self, pretrained_cfg)  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/model/base_module.py", line 144, in init_weights

    initialize(self, pretrained_cfg)  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/model/weight_init.py", line 610, in initialize

  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/model/weight_init.py", line 610, in initialize
    _initialize(module, cp_cfg)    _initialize(module, cp_cfg)
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/model/weight_init.py", line 518, in _initialize

  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/model/weight_init.py", line 518, in _initialize
    func(module)    func(module)
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/model/weight_init.py", line 490, in __call__

  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/model/weight_init.py", line 490, in __call__
    load_checkpoint(    load_checkpoint(
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/runner/checkpoint.py", line 642, in load_checkpoint

  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/runner/checkpoint.py", line 642, in load_checkpoint
    return _load_checkpoint_to_model(model, checkpoint, strict, logger,    return _load_checkpoint_to_model(model, checkpoint, strict, logger,
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/runner/checkpoint.py", line 607, in _load_checkpoint_to_model

    load_state_dict(model, state_dict, strict, logger)  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/runner/checkpoint.py", line 607, in _load_checkpoint_to_model

  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/runner/checkpoint.py", line 116, in load_state_dict
        load(module, state_dict)load_state_dict(model, state_dict, strict, logger)

  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/runner/checkpoint.py", line 92, in load
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/runner/checkpoint.py", line 116, in load_state_dict
    module._load_from_state_dict(local_state_dict, prefix, local_metadata,    load(module, state_dict)
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1380, in _load_from_state_dict

  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/runner/checkpoint.py", line 92, in load
    hook(state_dict, prefix, local_metadata, strict, missing_keys, unexpected_keys, error_msgs)    
  File "/home/nr4325/Desktop/Pose4/mmpose/mmpose/models/backbones/vision_transformer.py", line 414, in _prepare_pos_embed
module._load_from_state_dict(local_state_dict, prefix, local_metadata,    state_dict[name] = resize_pos_embed(state_dict[name],
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1380, in _load_from_state_dict

    hook(state_dict, prefix, local_metadata, strict, missing_keys, unexpected_keys, error_msgs)  File "/home/nr4325/Desktop/Pose4/mmpose/mmpose/models/utils/embed.py", line 44, in resize_pos_embed

  File "/home/nr4325/Desktop/Pose4/mmpose/mmpose/models/backbones/vision_transformer.py", line 414, in _prepare_pos_embed
    state_dict[name] = resize_pos_embed(state_dict[name],
  File "/home/nr4325/Desktop/Pose4/mmpose/mmpose/models/utils/embed.py", line 44, in resize_pos_embed
    assert L == src_h * src_w + num_extra_tokens, \    assert L == src_h * src_w + num_extra_tokens, \
AssertionError
AssertionError: The length of `pos_embed` (197) doesn't match the expected shape (14*14+0). Please check the`img_size` argument.: The length of `pos_embed` (197) doesn't match the expected shape (14*14+0). Please check the`img_size` argument.

/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1113401) of binary: /home/nr4325/miniconda3/envs/pose4/bin/python
Traceback (most recent call last):
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/distributed/run.py", line 715, in run
    elastic_launch(
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
tools/train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-12-13_06:10:23
  host      : skl-a-48.rc.rit.edu
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 1113402)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-12-13_06:10:23
  host      : skl-a-48.rc.rit.edu
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1113401)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
